/**
 * Test harness.
 *
 * The environment is set here BEFORE anything imports src/config/env.js, which
 * validates on first import. Nothing in the application reads a value that is
 * not set here — that is the point of the exercise.
 */
import process from 'node:process';

const TEST_ENV = {
  NODE_ENV: 'test',
  PORT: '4999',
  API_BASE_URL: 'http://localhost:4999',
  MONGODB_URI: 'mongodb://127.0.0.1:27017/lams_test',
  MONGODB_DB_NAME: 'lams_test',
  CLIENT_URL: 'http://localhost:5173',
  CORS_ORIGINS: 'http://localhost:5173',
  JWT_SECRET: 'test-only-access-secret-value-32-characters-min',
  JWT_REFRESH_SECRET: 'test-only-refresh-secret-value-32-characters-min',
  JWT_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '1d',
  JWT_ISSUER: 'lams-api-test',
  JWT_AUDIENCE: 'lams-client-test',
  BCRYPT_SALT_ROUNDS: '4', // fast on purpose; production uses the .env value
  AUTH_PROVIDER: 'local',
  DEFAULT_USER_ROLE: 'read_only',
  STORAGE_PROVIDER: 'local',
  STORAGE_LOCAL_PATH: './uploads-test',
  MAX_UPLOAD_BYTES: '26214400',
  LOG_LEVEL: 'error',

  // Document generation
  TEMPLATE_DIR: './server/templates',
  DOC_ORG_NAME: 'Test District',
  DOC_ORG_DIVISION: 'Land Acquisition and Management',
  DOC_ORG_ADDRESS: '1 Test Road, Testville, ST 00000',
  DOC_FOOTER_TEXT: 'Generated by LAMS (test)',
  DOC_LOCALE: 'en-US',
  DOC_CURRENCY: 'USD',

  // Automatic numbering
  FILE_NUMBER_PREFIX: 'LA',
  CONTRACT_NUMBER_PREFIX: 'CT',
  PO_NUMBER_PREFIX: 'PO',
  DOCUMENT_NUMBER_PREFIX: 'DOC',
  DISPOSITION_NUMBER_PREFIX: 'LD',
  NUMBER_SEQUENCE_PAD: '5',
  NUMBER_SEQUENCE_SCOPE: 'yearly',

  // Intake
  INTAKE_SOURCE: 'simulated',
  INTAKE_WEBHOOK_SECRET: 'test-intake-shared-secret',

  // GIS
  GIS_PROVIDER: 'sample',
  GIS_SAMPLE_DATA_PATH: './server/sample-data/parcels.geojson',

  // Feature toggles
  FEATURE_MAP: 'true',
  FEATURE_DOCUMENT_GENERATION: 'true',
  FEATURE_TIMBER: 'true',

  // Connectors — every one off by default, exactly as a fresh install ships.
  CONNECTOR_ARCGIS_ENABLED: 'false',
  CONNECTOR_ACCUFUND_ENABLED: 'false',
  CONNECTOR_CIVICPLUS_ENABLED: 'false',
  CONNECTOR_PAPERVISION_ENABLED: 'false',
  CONNECTOR_PERCH_ENABLED: 'false',
  CONNECTOR_LEGACY_ENABLED: 'false',

  // Background schedules never run during tests.
  SCHEDULER_ENABLED: 'false',
  SCHEDULER_TIMEZONE: 'UTC',
  REPORT_OUTPUT_DIR: './reports-test',
  REPORT_MONTHLY_SCHEDULE: '0 6 1 * *',
  REPORT_RETENTION_DAYS: '365',
  REPORT_MAX_ROWS: '50000',
};

// Force test values over anything inherited from a developer's shell or .env.
for (const [key, value] of Object.entries(TEST_ENV)) process.env[key] = value;

let mongoServer;
let mongooseRef;

/** Start an isolated database and return the app under test. */
export async function setupTestApp() {
  const uri = await startDatabase();
  process.env.MONGODB_URI = uri;

  const { connectDatabase } = await import('../../src/config/db.js');
  const { createApp } = await import('../../src/app.js');
  const mongoose = (await import('mongoose')).default;
  mongooseRef = mongoose;

  await connectDatabase(uri, 'lams_test');
  return createApp();
}

async function startDatabase() {
  // An explicit URI wins — useful in CI where a Mongo service is already running.
  if (process.env.TEST_MONGODB_URI) return process.env.TEST_MONGODB_URI;

  const { MongoMemoryServer } = await import('mongodb-memory-server');
  mongoServer = await MongoMemoryServer.create({ instance: { dbName: 'lams_test' } });
  return mongoServer.getUri();
}

export async function teardownTestApp() {
  if (mongooseRef) await mongooseRef.disconnect();
  if (mongoServer) await mongoServer.stop();
}

/** Empty every collection between tests so cases cannot leak into each other. */
export async function clearDatabase() {
  if (!mongooseRef) return;
  const { collections } = mongooseRef.connection;
  await Promise.all(Object.values(collections).map((collection) => collection.deleteMany({})));
}

/** Create a user with a known password and return it alongside a signed token. */
export async function createUser({
  email,
  password = 'correct-horse-battery-staple',
  role = 'read_only',
  modules = [],
  isActive = true,
  firstName = 'Test',
  lastName = 'User',
} = {}) {
  const { User } = await import('../../src/models/index.js');
  const { signAccessToken } = await import('../../src/services/tokenService.js');

  const user = new User({ firstName, lastName, email, role, modules, isActive, authProvider: 'local' });
  await user.setPassword(password);
  await user.save();

  return { user, password, token: signAccessToken(user) };
}

export const auth = (token) => ({ Authorization: `Bearer ${token}` });
